version: '3'
services:
  server:
    build:
      context: .
    ports:
      - 23:23
  db:
    image: mongo:6.0.6-jammy
    restart: always
    env_file:
      - .env
      - private.env
    volumes:
      - type: bind
        source: ./.private/mongodb
        target: /data/db
    ports:
      - 27017:27017