version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: rinoramud
    ports:
      - 5432:5432
  testdb:
    image: postgres
    restart: always
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: devtest
      POSTGRES_PASSWORD: devtest
      POSTGRES_DB: rinoratest
    ports:
      - 5433:5432
