version: '3'
services:
  server:
    build:
      context: .
    ports:
      - 23:23
  db:
    image: mongo:6.0.6-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASS
    volumes:
      - type: bind
        source: ./.private/mongodb
        target: /data/db
    ports:
      - 27017:27017