version: '3'
services:
  mongodbdev:
    image: mongo:6.0.6-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev
    volumes:
      - type: bind
        source: ./.private/mongodb
        target: /data/db